added prune before installing in integrationTests.yaml file

diff --git a/.github/workflows/integrationTests.yaml b/.github/workflows/integrationTests.yaml
--- a/.github/workflows/integrationTests.yaml
+++ b/.github/workflows/integrationTests.yaml
@@ -1,44 +1,51 @@
 name: Integration Tests
+
 on:
-    push:
-        branches:
-            - "*"
-    pull_request_target:
-        branches:
-            - "*"
+  push:
+    branches:
+      - "*"
+  pull_request_target:
+    branches:
+      - "*"
 
 jobs:
-    integration-tests:
-        runs-on: ubuntu-latest
-        env:
-            OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
-        steps:
-            - uses: actions/checkout@v4
+  integration-tests:
+    runs-on: ubuntu-latest
+    env:
+      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
 
-            - uses: pnpm/action-setup@v3
-              with:
-                  version: 9.4.0
+      - name: Set up PNPM
+        uses: pnpm/action-setup@v3
+        with:
+          version: 9.4.0
 
-            - uses: actions/setup-node@v4
-              with:
-                  node-version: "23"
-                  cache: "pnpm"
+      - name: Set up Node.js
+        uses: actions/setup-node@v4
+        with:
+          node-version: "23"
+          cache: "pnpm"
 
-            - name: Clean up
-              run: pnpm clean
+      - name: Clean up previous builds and caches
+        run: |
+          pnpm store prune
+          pnpm clean
+          rm -rf node_modules .pnpm-store packages/*/node_modules  # Removes all node_modules directories
 
-            - name: Install dependencies
-              run: pnpm install -r --no-frozen-lockfile
+      - name: Install dependencies with frozen lockfile
+        run: pnpm install --frozen-lockfile -r
 
-            - name: Build packages
-              run: pnpm build
+      - name: Build packages
+        run: pnpm build
 
-            - name: Check for API key
-              run: |
-                  if [ -z "$OPENAI_API_KEY" ]; then
-                      echo "Error: OPENAI_API_KEY is not set."
-                      exit 1
-                  fi
+      - name: Check for API key
+        run: |
+          if [ -z "$OPENAI_API_KEY" ]; then
+            echo "Error: OPENAI_API_KEY is not set."
+            exit 1
+          fi
 
-            - name: Run integration tests
-              run: pnpm run integrationTests
+      - name: Run integration tests
+        run: pnpm run integrationTests
